sonar.projectName=symfony-the-fast-track
sonar.projectVersion=20241211
sonar.projectKey=dmytrii.lysak_symfony-the-fast-track_e194f6e1-d1e5-4e18-9a29-80e5ece99609
sonar.qualitygate.wait=true
sonar.exclusions="owasp-dependency-report/*", "zap-report/*"
